version: "3.3"
services:
  db:
    image: percona:5.6.36
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./mysql_config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
